name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If this is your first time reporting a bug, please read our [guide](https://jasp-stats.org/2018/03/29/request-feature-report-bug-jasp/) first. 
  - type: dropdown
    id: jasp-version
    attributes:
      label: JASP Version
      description: What version of JASP are you running?
      options:
        - Others
        - 0.9.2
        - 0.12
        - 0.13
        - 0.13.1
        - 0.14
        - 0.15
        - 0.15 (Nightly)
        - 0.15 (Development)
    validations:
      required: true
  - type: dropdown
    id: jasp-analysis
    attributes:
      label: JASP Module
      description:  What JASP analysis are you seeing the problem on?
      multiple: true
      options:
        - jaspDescriptives
        - jaspAnova
        - jaspFactor
        - jaspFrequencies
        - jaspRegression
        - jaspTTests
        - jaspMixedModels
        - jaspAudit
        - jaspBain
        - jaspNetwork
        - jaspSem
        - jaspMachineLearning
        - jaspSummaryStatistics
        - jaspMetaAnalysis
        - jaspDistributions
        - jaspEquivalenceTTests
        - jaspJags
        - jaspReliability
        - jaspVisualModeling
        - jaspLearnBayes
        - jaspProphet
        - jaspProcessControl
        - jaspCircular
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      description: Please mention the name and version of the Operation System that you are using?
      placeholder: "e.g., Window 10, macOS Big Sur 11.6"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please tell us what happened. In addition, please drag-and-drop any related files, or screenshot (if any) to this area. **If you would like to upload a JASP file, please compress your (.jasp) file before uploading it to GitHub.** In addition, if you would prefer to not make your data publicly available, you can send your files directly to us, issues@jasp-stats.org.
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Please tell us what should have happened instead of the bug. In addition, you can include any images or files showcasing the correct behaviour.
      placeholder: "This should have happened instead!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Can you reproduce the bug? If so, please let us know what steps you take to reproduce this bug.
      placeholder: "1."
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log (if any)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
  - type: checkboxes
     id: final-checklist
     attributes:
       label: Final Checklist
       description: Please take a moment and make sure that you have filled all fields as accurately as possible; otherwise, we will not be able to track and resolve your issue.
       options:   
          - label: I have included a screenshot showcasing the issue, if any.
            required: true
